apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elastic-system
data:
  beat.yml: |
    filebeat.inputs:
    - type: filestream
      id: quickstart
      paths:
      - /var/log/quickstart/logs/**/*
    - type: aws-s3
      bucket_arn: arn:aws:s3:::test-s3-bucket
      access_key_id: CHANGEME
      secret_access_key: CHANGEME
      number_of_workers: 5
    output.elasticsearch:
      hosts: ["https://quickstart-es-http:9200"]
      api_key: ""
      ssl:
        certificate_authorities: ["/mnt/es-internal-http-certs/ca.crt"]
        certificate: "/mnt/es-internal-http-certs/tls.crt"
        key: "/mnt/es-internal-http-certs/tls.key"
