apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: elastic
  namespace: elastic-system
spec:
  type: filebeat
  version: 8.11.1
  elasticsearchRef:
    name: elastic
  deployment:
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: app
                  operator: In
                  values:
                  - monitoring
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
          - name: logs
            mountPath: /var/log/app/logs
          - name: filebeat-cm
            mountPath: /etc/beat.yml
            subPath: beat.yml
            readOnly: true
          - name: filebeat-data
            mountPath: /usr/share/filebeat/data
        tolerations:
        - key: "app"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
        volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: filebeat-cm
          configMap:
            name: filebeat-config
            defaultMode: 0600
        - name: filebeat-data
          persistentVolumeClaim:
            claimName: filebeat-pvc
