apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  count: 1
  elasticsearchRefs:
    - name: quickstart
      clusterName: quickstart
  version: 8.11.1
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          grok {
            match => [ "message", "%{TIMESTAMP_ISO8601:logdate}" ]
          }
          date {
            match => [ "logdate", "YYYY-MM-dd HH:mm:ss,SSS"]
            target => "@timestamp"
          }
        }
        output {
          elasticsearch {
            hosts => [ "https://quickstart-es-http:9200" ]
            api_key => "Xu1gXowB89x_VaGH64YK:TDtrPjPBQy6EHNSTpfEadA"
            ssl_certificate_authorities => '/mnt/es-http-certs-internal/ca.crt'
            data_stream => "true"
            data_stream_type => "logs"
            data_stream_dataset => "quickstart"
            data_stream_namespace => "logstash"
          }
          stdout { codec => rubydebug }
        }
  # Create an ClusterIP service for ingesting inputs from filebeat
  services:
    - name: beats
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
  podTemplate:
    spec:
      volumes:
        - name: quickstart-es-http-certs-internal
          secret:
            secretName: quickstart-es-http-certs-internal
      containers:
        - name: logstash
          volumeMounts:
            - name: quickstart-es-http-certs-internal
              mountPath: /mnt/es-http-certs-internal
              readOnly: true
